name: frase_da_semana
description: Um aplicativo de Frases da semana

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  audioplayer: ^0.8.1
  flutter_date_pickers: ^0.1.5
  audioplayers: ^0.15.1
  flutter_icons: ^1.1.0
  brasil_fields: ^0.3.0
  firedart: ^0.8.2
  package_info: ^0.4.1
  sentry: ^3.0.1
  file_picker_cross: ^4.2.2
  chewie: ^0.9.10
  flutter_local_notifications: ^1.4.3
  hive_flutter: ^0.3.0+2
  hive: ^1.4.1+1
  device_info: ^0.4.2+3
  firebase_messaging: ^6.0.13
  hasura_connect: ^1.2.1+1
  after_layout: ^1.0.7+2
  video_player: ^0.10.8+1
  chewie_audio: ^1.0.0+1
  carousel_slider: ^2.3.1
  firebase_core: ^0.4.4+3
  firebase_storage: ^3.1.5
  path_provider: 1.6.18
  path: ^1.6.4
  image_picker: ^0.6.5
  cached_network_image: ^2.3.0-rc
  progress_dialog: ^1.2.4
  intl: ^0.16.1
  sprintf: ^4.0.2 
  flutter_staggered_grid_view: ^0.3.0 
  diacritic: ^0.1.1
  flutter_audio_recorder: ^0.5.5
  dio: ^3.0.9
  rxdart: 0.24.0
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+2
  bloc_pattern: ^2.5.1
  curved_navigation_bar: ^0.3.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
dependency_overrides: 
  path: 1.7.0

dev_dependencies:
  hive_generator: ^0.7.0+2
  mobx_codegen: ^1.0.2
  build_runner: ^1.8.0
  mockito: ^4.1.1
 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - imagens/ 


scripts:
    build: flutter pub run build_runner build --delete-conflicting-outputs
    watch: flutter pub run build_runner watch --delete-conflicting-outputs
    clean: flutter pub run build_runner clean
    compilar: flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
